name: React App Tabs to Test

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    environment: Test
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      - name: Debug Secrets
        run: |
          echo "LNBITS_NODE_URL is ${{ secrets.LNBITS_NODE_URL }}"
          echo "LNBITS_USERNAME is ${{ secrets.LNBITS_USERNAME }}"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        env:
          CI: false
          REACT_APP_LNBITS_NODE_URL: ${{ secrets.LNBITS_NODE_URL }}
          REACT_APP_LNBITS_USERNAME: ${{ secrets.LNBITS_USERNAME }}
          REACT_APP_LNBITS_PASSWORD: ${{ secrets.LNBITS_PASSWORD }}
          REACT_APP_LNBITS_ADMINKEY: ${{ secrets.LNBITS_ADMINKEY }}
          REACT_APP_LNBITS_STORE_ID: ${{ secrets.LNBITS_STORE_ID }} 
          REACT_APP_TENANT_ID:  ${{ secrets.TENANT_ID }}
          REACT_APP_AAD_CLIENT_ID:  ${{ secrets.AAD_CLIENT_ID }}
          REACT_APP_LNBITS_STORE_OWNER_EMAIL: ${{ secrets.LNBITS_STORE_OWNER_EMAIL }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/tabs"
          api_location: ""
          output_location: "build"
